### ISSUE TITLE
How to sample from the pre-trained model?

### ISSUE THREAD

**Issue by Crista23** [Sanqiang/text_simplification#12]
Can you please share the command to sample from the pre-trained model you made available? Thanks!

**Comment by Crista23** [comment]
When running the command:

       python model/test.py -test_ckpt text_simplification/pretrained_model/ckpt

I get the error below:

      Traceback (most recent call last):
      File "model/test.py", line 341, in <module>
      test(config, ckpt)
      File "model/test.py", line 43, in test
      val_data = ValData(model_config)
     File "text_simplification/data_generator/val_data.py", line 23, in __init__
     self.vocab_simple = Vocab(model_config, vocab_simple_path)
     File "text_simplification/data_generator/vocab.py", line 20, in __init__
     self.populate_vocab()
      File "text_simplification/data_generator/vocab.py", line 51, in populate_vocab
      topcount = min(topcount, self.model_config.top_count)
      AttributeError: WikiTransTestConfig instance has no attribute 'top_count'

**Comment by Sanqiang** [comment]
WikiTransTestConfig is a config I am testing (not included in the paper).
Could you try another config, such as WikiDressLargeDefault for Wikilarge
